name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS (Backend)
        uses: appleboy/ssh-action@v1
        with:
          host: 72.62.192.246
          username: root
          port: 2222
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/carefoundation/backend
            git pull origin main
            npm install
            pm2 restart care-backend
